// Mocks generated by Mockito 5.1.0 from annotations
// in clear_architecture/test/features/user_authentication/data/models/user_details_model_test.dart.
// Do not manually edit this file.

import 'package:clear_architecture/features/user_authentication/data/models/user_details_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserDetailsModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDetailsModel extends _i1.Mock implements _i2.UserDetailsModel {
  MockUserDetailsModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userID =>
      (super.noSuchMethod(Invocation.getter(#userID), returnValue: '')
          as String);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
